# Generated by Django 4.0.1 on 2022-05-27 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='conc_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='concluded',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
